server:
  error:
    whitelabel:
      enabled: true
  port: 8082
security:
  basic:
    enabled: false
spring:
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  thymeleaf:
    mode: LEGACYHTML5
    cache: false
    suffix: .html
    prefix: classpath:/templates/
    encoding: utf-8
    content-type: text/html
  datasource:
    name: blog2.0
#    url: jdbc:mysql://127.0.0.1:3306/shiro?useUnicode=true&characterEncoding=UTF-8
#    username: root
#    password: 123456
    #url: jdbc:mysql://192.168.199.180:3306/dev_njair?useUnicode=true&characterEncoding=UTF-8
    #username: root
    #password: xsscd
    url: jdbc:mysql://39.108.158.254:3306/blog2.0?useUnicode=true&characterEncoding=UTF-8
    username: root
    password: 940707you
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  http:
    multipart:
      max-file-size: 30Mb
      max-request-size: 30Mb
#  freemarker:
#    suffix: .ftl
#    template-loader-path: classpath:/templates/
#LOG
#logging:
  #config: classpath:log4j2.xml
mybatis:
  type-aliases-package: com.youjiniot.domain
  #mapperLocations: classpath:mybatis/*.xml
  configuration:
    #下划线转驼峰
    mapUnderscoreToCamelCase: true
  mapper-locations: mybatis/**/*Mapper.xml
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  pageSizeZero: true
  params: count=countSql

